name = str(input('Qual o seu nome completo: ')).strip()
M = name.upper()
m = name.lower()
j = (len(name) - name.count(' '))
d = name.split()
i = len(d[0])
print('Seu nome em letra maiúscula é {}'.format(M))
print('Seu nome em letra minúscula é {}'.format(m))
print('A quantidade de letras do seu nome completo é {}'.format(j))
print('A quantidade de letras do seu primeiro nome é {}'.format(i))
